version: "3.9"

services:
  kotlin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - amass
    environment:
      AMASS_BINARY_PATH: /opt/amass/amass

  amass:
    image: caffix/amass:latest
    container_name: amass
    volumes:
      - ./amass-output:/opt/amass/output
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
